### ISSUE TITLE
Can't edit a document in Google Apps

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-googleapps#74]
Preconditions: Office Server must be started.

Steps to reproduce:

1. Login with Google owner
2. Create a page
3. Add an office attachment docx, pptx, xlsx
4. Go to Attachments tab
5. Click 'Edit in Google Apps'
6. Click 'Confirm Edit in Google Apps' (if the file is for the first time uploaded to Google Drive) 
![ConfirmEdit](https://github.com/xwikisas/application-googleapps/assets/40691112/f83cd8ec-bf2e-4c7d-befa-4ef404d325a2)

Expected results: The user is directed to a page where the document can be edited.

Actual results: An error appears

![EditResult](https://github.com/xwikisas/application-googleapps/assets/40691112/8affdd30-af09-41c0-9f67-782882fb7e7e)

`Failed to execute the [velocity] macro. Cause: [Cannot invoke method getMimeType() on null object]. Click on this message for details.

org.xwiki.rendering.macro.MacroExecutionException: Failed to evaluate Velocity Macro for content [#set($gagroovy = $xwiki.parseGroovyFromPage("GoogleApps.Groovy"))
#set($ok = $gagroovy.init($xwiki, $context, $doc))
#if($gagroovy.active && $gagroovy.useDrive)
  #set($gdoc = $gagroovy.getGoogleDocument($request.page, $request.name))
  #if($request.confirm)
  {{translation key='googleapps.editInGA.uploading'/}}
   #set($gdoc = $gagroovy.saveAttachmentToGoogle($request.page, $request.name))
  #end

  #if($gdoc)
  {{translation key='googleapps.editInGA.isInGDrive'/}}

  (% class="buttonwrapper" %)
  {{html clean=false}}<a href="${gdoc.editLink}" target="_blank">$services.localization.render("googleapps.edit.editingoogle.button")</a>{{/html}}

  $services.localization.render("googleapps.edit.desc")

  (% class="buttonwrapper" %)[[$services.localization.render("googleapps.edit.retrieve.button")>>RetrieveFromGoogleApps||queryString="page=${escapetool.url($request.page)}&name=${escapetool.url($request.name)}&url=${escapetool.url($gdoc.exportLink)}&id=${gdoc.id}"]]
  #else
    #if($gagroovy.canSyncFile($request.name))
      {{translation key='googleapps.editInGA.notYetInGDrive'/}}

      (% class="buttonwrapper" %)[[$services.localization.render("googleapps.edit.confirm")>>||queryString="page=${escapetool.url($request.page)}&name=${escapetool.url($request.name)}&confirm=1"]]
    #else
      {{translation key='googleapps.editInGA.notSupportedFormat'/}}
    #end
  #end
#else
  {{translation key='googleapps.error.driveDisabled'/}}
#end]

 at org.xwiki.rendering.internal.macro.velocity.VelocityMacro.evaluateString(VelocityMacro.java:135)

 at org.xwiki.rendering.internal.macro.velocity.VelocityMacro.evaluateString(VelocityMacro.java:51)

 at org.xwiki.rendering.macro.script.AbstractScriptMacro.evaluateBlock(AbstractScriptMacro.java:279)

 at org.xwiki.rendering.macro.script.AbstractScriptMacro.execute(AbstractScriptMacro.java:182)

 at org.xwiki.rendering.macro.script.AbstractScriptMacro.execute(AbstractScriptMacro.java:58)

 at org.xwiki.rendering.internal.transformation.macro.MacroTransformation.transform(MacroTransformation.java:309)

 at org.xwiki.rendering.internal.transformation.DefaultRenderingContext.transformInContext(DefaultRenderingContext.java:183)

 at org.xwiki.rendering.internal.transformation.DefaultTransformationManager.performTransformations(DefaultTransformationManager.java:88)

 at org.xwiki.display.internal.DocumentContentAsyncExecutor.executeInCurrentExecutionContext(DocumentContentAsyncExecutor.java:395)

 at org.xwiki.display.internal.DocumentContentAsyncExecutor.execute(DocumentContentAsyncExecutor.java:268)

 at org.xwiki.display.internal.DocumentContentAsyncRenderer.execute(DocumentContentAsyncRenderer.java:112)

 at org.xwiki.rendering.async.internal.block.AbstractBlockAsyncRenderer.render(AbstractBlockAsyncRenderer.java:157)

 at org.xwiki.rendering.async.internal.block.AbstractBlockAsyncRenderer.render(AbstractBlockAsyncRenderer.java:54)

 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.syncRender(DefaultAsyncRendererExecutor.java:290)

 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.render(DefaultAsyncRendererExecutor.java:267)

 at org.xwiki.rendering.async.internal.block.DefaultBlockAsyncRendererExecutor.execute(DefaultBlockAsyncRendererExecutor.java:125)

 at org.xwiki.display.internal.DocumentContentDisplayer.display(DocumentContentDisplayer.java:67)

 at org.xwiki.display.internal.DocumentContentDisplayer.display(DocumentContentDisplayer.java:43)

 at org.xwiki.display.internal.DefaultDocumentDisplayer.display(DefaultDocumentDisplayer.java:96)

 at org.xwiki.display.internal.DefaultDocumentDisplayer.display(DefaultDocumentDisplayer.java:39)

 at org.xwiki.sheet.internal.SheetDocumentDisplayer.display(SheetDocumentDisplayer.java:123)

 at org.xwiki.sheet.internal.SheetDocumentDisplayer.display(SheetDocumentDisplayer.java:52)

 at org.xwiki.display.internal.ConfiguredDocumentDisplayer.display(ConfiguredDocumentDisplayer.java:68)

 at org.xwiki.display.internal.ConfiguredDocumentDisplayer.display(ConfiguredDocumentDisplayer.java:42)

 at com.xpn.xwiki.doc.XWikiDocument.display(XWikiDocument.java:1355)

 at com.xpn.xwiki.doc.XWikiDocument.getRenderedContent(XWikiDocument.java:1492)

 at com.xpn.xwiki.doc.XWikiDocument.displayDocument(XWikiDocument.java:1441)

 at com.xpn.xwiki.doc.XWikiDocument.displayDocument(XWikiDocument.java:1410)

 at com.xpn.xwiki.api.Document.displayDocument(Document.java:786)

 at jdk.internal.reflect.GeneratedMethodAccessor700.invoke(Unknown Source)

 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

 at java.base/java.lang.reflect.Method.invoke(Method.java:566)

 at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:571)

 at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:554)

 at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:221)

 at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:368)

 at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:704)

 at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:75)

 at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:242)

 at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)

 at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)

 at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:190)

 at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)

 at org.xwiki.velocity.internal.directive.TryCatchDirective.render(TryCatchDirective.java:86)

 at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:304)

 at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)

 at org.apache.velocity.Template.merge(Template.java:358)

 at org.apache.velocity.Template.merge(Template.java:262)

 at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluate(DefaultVelocityEngine.java:280)

 at com.xpn.xwiki.render.DefaultVelocityManager.evaluate(DefaultVelocityManager.java:321)

 at com.xpn.xwiki.internal.template.VelocityTemplateEvaluator.evaluateContent(VelocityTemplateEvaluator.java:95)

 at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.evaluateContent(TemplateAsyncRenderer.java:222)

 at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.renderVelocity(TemplateAsyncRenderer.java:177)

 at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.render(TemplateAsyncRenderer.java:138)

 at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.render(TemplateAsyncRenderer.java:54)

 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.lambda$syncRender$0(DefaultAsyncRendererExecutor.java:284)

 at com.xpn.xwiki.internal.security.authorization.DefaultAuthorExecutor.call(DefaultAuthorExecutor.java:98)

 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.syncRender(DefaultAsyncRendererExecutor.java:284)

 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.render(DefaultAsyncRendererExecutor.java:267)

 at org.xwiki.rendering.async.internal.block.DefaultBlockAsyncRendererExecutor.render(DefaultBlockAsyncRendererExecutor.java:154)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.render(InternalTemplateManager.java:843)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.renderFromSkin(InternalTemplateManager.java:805)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.render(InternalTemplateManager.java:792)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.renderNoException(InternalTemplateManager.java:747)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.renderNoException(InternalTemplateManager.java:739)

 at com.xpn.xwiki.internal.template.DefaultTemplateManager.renderNoException(DefaultTemplateManager.java:79)

 at com.xpn.xwiki.internal.template.DefaultTemplateManager.renderNoException(DefaultTemplateManager.java:73)

 at org.xwiki.template.script.TemplateScriptService.render(TemplateScriptService.java:54)

 at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)

 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

 at java.base/java.lang.reflect.Method.invoke(Method.java:566)

 at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:571)

 at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:554)

 at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:221)

 at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:368)

 at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:492)

 at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)

 at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:218)

 at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:331)

 at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:261)

 at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:304)

 at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)

 at org.apache.velocity.Template.merge(Template.java:358)

 at org.apache.velocity.Template.merge(Template.java:262)

 at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluate(DefaultVelocityEngine.java:280)

 at com.xpn.xwiki.render.DefaultVelocityManager.evaluate(DefaultVelocityManager.java:321)

 at com.xpn.xwiki.internal.template.VelocityTemplateEvaluator.evaluateContent(VelocityTemplateEvaluator.java:95)

 at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.evaluateContent(TemplateAsyncRenderer.java:222)

 at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.renderVelocity(TemplateAsyncRenderer.java:177)

 at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.render(TemplateAsyncRenderer.java:138)

 at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.render(TemplateAsyncRenderer.java:54)

 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.lambda$syncRender$0(DefaultAsyncRendererExecutor.java:284)

 at com.xpn.xwiki.internal.security.authorization.DefaultAuthorExecutor.call(DefaultAuthorExecutor.java:98)

 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.syncRender(DefaultAsyncRendererExecutor.java:284)

 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.render(DefaultAsyncRendererExecutor.java:267)

 at org.xwiki.rendering.async.internal.block.DefaultBlockAsyncRendererExecutor.render(DefaultBlockAsyncRendererExecutor.java:154)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.render(InternalTemplateManager.java:843)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.renderFromSkin(InternalTemplateManager.java:805)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.render(InternalTemplateManager.java:792)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.renderNoException(InternalTemplateManager.java:747)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.renderNoException(InternalTemplateManager.java:739)

 at com.xpn.xwiki.internal.template.DefaultTemplateManager.renderNoException(DefaultTemplateManager.java:79)

 at com.xpn.xwiki.internal.template.DefaultTemplateManager.renderNoException(DefaultTemplateManager.java:73)

 at org.xwiki.template.script.TemplateScriptService.render(TemplateScriptService.java:54)

 at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)

 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

 at java.base/java.lang.reflect.Method.invoke(Method.java:566)

 at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:571)

 at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:554)

 at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:221)

 at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:368)

 at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:492)

 at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)

 at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:218)

 at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:331)

 at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:261)

 at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:304)

 at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)

 at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:171)

 at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)

 at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)

 at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:190)

 at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)

 at org.apache.velocity.Template.merge(Template.java:358)

 at org.apache.velocity.Template.merge(Template.java:262)

 at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluate(DefaultVelocityEngine.java:280)

 at com.xpn.xwiki.render.DefaultVelocityManager.evaluate(DefaultVelocityManager.java:321)

 at com.xpn.xwiki.internal.template.VelocityTemplateEvaluator.evaluateContent(VelocityTemplateEvaluator.java:95)

 at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.evaluateContent(TemplateAsyncRenderer.java:222)

 at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.renderVelocity(TemplateAsyncRenderer.java:177)

 at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.render(TemplateAsyncRenderer.java:138)

 at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.render(TemplateAsyncRenderer.java:54)

 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.lambda$syncRender$0(DefaultAsyncRendererExecutor.java:284)

 at com.xpn.xwiki.internal.security.authorization.DefaultAuthorExecutor.call(DefaultAuthorExecutor.java:98)

 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.syncRender(DefaultAsyncRendererExecutor.java:284)

 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.render(DefaultAsyncRendererExecutor.java:267)

 at org.xwiki.rendering.async.internal.block.DefaultBlockAsyncRendererExecutor.render(DefaultBlockAsyncRendererExecutor.java:154)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.render(InternalTemplateManager.java:843)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.renderFromSkin(InternalTemplateManager.java:805)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.renderFromSkin(InternalTemplateManager.java:785)

 at com.xpn.xwiki.internal.template.InternalTemplateManager.render(InternalTemplateManager.java:771)

 at com.xpn.xwiki.internal.template.DefaultTemplateManager.render(DefaultTemplateManager.java:91)

 at com.xpn.xwiki.internal.template.DefaultTemplateManager.render(DefaultTemplateManager.java:85)

 at com.xpn.xwiki.XWiki.evaluateTemplate(XWiki.java:2563)

 at com.xpn.xwiki.web.Utils.parseTemplate(Utils.java:180)

 at com.xpn.xwiki.web.XWikiAction.execute(XWikiAction.java:651)

 at com.xpn.xwiki.web.XWikiAction.execute(XWikiAction.java:339)

 at com.xpn.xwiki.web.LegacyActionServlet.service(LegacyActionServlet.java:114)

 at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)

 at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1419)

 at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)

 at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1624)

 at com.xpn.xwiki.web.ActionFilter.doFilter(ActionFilter.java:122)

 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)

 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)

 at org.xwiki.wysiwyg.filter.ConversionFilter.doFilter(ConversionFilter.java:61)

 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)

 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)

 at org.xwiki.container.servlet.filters.internal.SetHTTPHeaderFilter.doFilter(SetHTTPHeaderFilter.java:63)

 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)

 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)

 at org.xwiki.resource.servlet.RoutingFilter.doFilter(RoutingFilter.java:132)

 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)

 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)

 at org.xwiki.container.servlet.filters.internal.SavedRequestRestorerFilter.doFilter(SavedRequestRestorerFilter.java:208)

 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)

 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)

 at org.xwiki.container.servlet.filters.internal.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:111)

 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)

 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)

 at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:164)

 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)

 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)

 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:506)

 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)

 at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)

 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)

 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)

 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)

 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)

 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1378)

 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)

 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463)

 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)

 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)

 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300)

 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)

 at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)

 at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)

 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)

 at org.eclipse.jetty.server.Server.handle(Server.java:562)

 at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:418)

 at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:675)

 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:410)

 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)

 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)

 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)

 at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)

 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)

 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)

 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)

 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)

 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)

 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)

 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)

 at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: org.xwiki.velocity.XWikiVelocityException: Failed to evaluate content with namespace [xwiki:GoogleApps.EditInGoogleApps]

 at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluate(DefaultVelocityEngine.java:289)

 at com.xpn.xwiki.render.DefaultVelocityManager.evaluate(DefaultVelocityManager.java:321)

 at org.xwiki.rendering.internal.macro.velocity.VelocityMacro.evaluateString(VelocityMacro.java:127)

 ... 205 more

Caused by: org.apache.velocity.exception.MethodInvocationException: Invocation of method 'saveAttachmentToGoogle' in  class GoogleAppsGroovy threw exception java.lang.NullPointerException: Cannot invoke method getMimeType() on null object at xwiki:GoogleApps.EditInGoogleApps[line 7, column 24]

 at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:308)

 at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:235)

 at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:368)

 at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:704)

 at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:75)

 at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:242)

 at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)

 at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:171)

 at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)

 at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:171)

 at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)

 at org.apache.velocity.Template.merge(Template.java:358)

 at org.apache.velocity.Template.merge(Template.java:262)

 at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluate(DefaultVelocityEngine.java:280)

 ... 207 more

Caused by: java.lang.NullPointerException: Cannot invoke method getMimeType() on null object

 at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)

 at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)

 at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)

 at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)

 at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)

 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)

 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)

 at GoogleAppsGroovy.saveAttachmentToGoogle(Script_765581af138cbaea069885f002925edc.groovy:717)

 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

 at java.base/java.lang.reflect.Method.invoke(Method.java:566)

 at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:571)

 at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:554)

 at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:221)

 ... 219 more`

Environment: Windows 11, XWiki 14.10.15, Chrome 117, Google Apps Integration (Pro) 2.6

**Comment by ane-gabriela** [comment]
Reproducing on XWiki 15.10.5 with MySQL 8.3, Edge 121 and Google Apps Integration (Pro) 2.6

![Step1](https://github.com/xwikisas/application-googleapps/assets/40691112/b8586d05-5722-46a5-abe1-e8c75296ad85)

![Step2](https://github.com/xwikisas/application-googleapps/assets/40691112/cc6c3d26-f916-4830-ad16-2a4d7df8b0db)

![Docx file](https://github.com/xwikisas/application-googleapps/assets/40691112/24cbb8dd-9fc8-4a92-82c3-9077ca917ca7)

**Comment by ane-gabriela** [comment]
Issue reproducing on Cloud XWiki 15.10.8, Google Apps Integration (Pro) 2.6.1, Chrome 125

![EditGADoc](https://github.com/xwikisas/application-googleapps/assets/40691112/dc804e1b-24c5-4749-9fa8-2882dabcba1d)

**Comment by ilieandriuta** [comment]
Issue reproduced too on XWiki 16.4.0 (PostgreSQL 16/ Tomcat 9.0.89) using Google Apps Integration (Pro) 2.6.1. In my case, when tried to edit a .doc file, it just said "This document format cannot be synchronized with Google Drive.

![image](https://github.com/xwikisas/application-googleapps/assets/32512703/26ee8738-eba5-4a9d-b4da-513c7bde1b84)

**Comment by ilieandriuta** [comment]
Reproducing the issue as well on XWiki 17.10.3 (MySQL 9.3/ Tomcat 11.0.18) using Google Apps Integration (Pro) 3.2.1 as observed in the screenshot above. The message is: "This document format cannot be synchronized with Google Drive."

**Comment by Farcasut** [comment]
> Reproducing the issue as well on XWiki 17.10.3 (MySQL 9.3/ Tomcat 11.0.18) using Google Apps Integration (Pro) 3.2.1 as observed in the screenshot above. The message is: "This document format cannot be synchronized with Google Drive."

The doc format doesn't seem to be supported, but with the formats that Gabriela mentioned in the issue, the code works fine. See video.

https://github.com/user-attachments/assets/ac6e7433-7277-4c90-9f92-9a89eef013b1

**Comment by Farcasut** [comment]
You can not retrieve the document from google after you edit it, but I think this is intended.

```
GET https://www.googleapis.com/download/drive/v2/files/10ncgvKlHYzG37YohGu80H9pMijyjw18s0cjwKXQmX2w?alt=media
{
  "code": 403,
  "errors": [
    {
      "domain": "global",
      "location": "alt",
      "locationType": "parameter",
      "message": "Only files with binary content can be downloaded. Use Export with Docs Editors files.",
      "reason": "fileNotDownloadable"
    }
  ],
  "message": "Only files with binary content can be downloaded. Use Export with Docs Editors files."
}


```

**Comment by Farcasut** [comment]
Google doesn't allow the retrieval of files that are not binary anymore

**Comment by oanalavinia** [comment]
> Google doesn't allow the retrieval of files that are not binary anymore

@Farcasut so this is actually a `won't fix`?

**Comment by Farcasut** [comment]
> > Google doesn't allow the retrieval of files that are not binary anymore
> 
> [@Farcasut](https://github.com/Farcasut) so this is actually a `won't fix`?

Sorry for the confusion, but the issue from this ticket is already solved the problem that I was describing above is a separate manner and I've created https://github.com/xwikisas/application-googleapps/issues/109
